### ISSUE TITLE
1.0.3.2版本无法启动，报错NoClassDefFoundError

### ISSUE THREAD

**Issue by TCreopargh** [0999312/Sakura_mod#111]
#### MOD版本 - Mod version:
1.0.3.2

#### Forge版本 - Forge version:
14.23.5.2854

#### 单人/多人游戏？ - Singleplayer or Multiplayer:
单人

#### 完整的MOD列表 - Installed mods:
见崩溃报告

## 崩溃报告的链接 - Link to full crash log
https://paste.ubuntu.com/p/zRTjtvXHSP/

## 问题描述 - Description of the problem
1.0.3.2版本安装后无法启动，报错java.lang.NoClassDefFoundError: snownee/cuisine/blocks/BlockBamboo

#### 产生Bug的步骤 - How to reproduce:
1. 安装sakura 1.0.3.2
2. 安装MMLib2.1.0
3. crash

可能是和Cuisine的问题，因为我看更新日志添加了对Cuisine的兼容但是我没有安装Cuisine，报错也是与这个相关。

**Comment by 0999312** [comment]
问题已收到，请等待修复。

**Comment by 0999312** [comment]
请更新至1.0.3.3
