### ISSUE TITLE
关于1.0.4梅树树叶的崩溃

### ISSUE THREAD

**Issue by mcBegins2Snow** [0999312/Sakura_mod#113]
#### MOD版本 - Mod version:

sakura 1.0.4
前置 2.0.0

#### Forge版本 - Forge version:

14.23.5.2854

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

单人

#### 完整的MOD列表 - Installed mods:

http://www.s3tu.com/images/2020/11/25/17a9ea.png

## 崩溃报告的链接 - Link to full crash log

https://paste.ubuntu.com/p/9w9khGgBzR/

#### 产生Bug的步骤 - How to reproduce:

1.在主世界到处跑图；
2.此崩溃不一定什么时候发生，根据崩溃报告，第7行的umeleaves可确定此崩溃与梅树树叶有关；
3.玩家自动种下梅树树苗，然后用骨粉催熟不会崩溃。

**Comment by 0999312** [comment]
1.0.4.1早已修复此问题
