### ISSUE TITLE
无法进行樱花钱币大于64个的村民交易

### ISSUE THREAD

**Issue by mcBegins2Snow** [0999312/Sakura_mod#114]
#### MOD版本 - Mod version:

sakura 1.0.4.1
前置 2.0.0

#### Forge版本 - Forge version:

14.23.5.2854

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

单人

#### 完整的MOD列表 - Installed mods:

http://www.s3tu.com/images/2020/11/26/2bb0ab.png

#### 产生Bug的步骤 - How to reproduce:

1.与酒品贩子交易；
2.看到一个要74个樱花钱币的交易，试图进行交易；
3.放入两组（128个）樱花钱币，无输出物品；
4.在原版，大于64绿宝石的村民交易不存在。
http://www.s3tu.com/images/2020/11/26/2020-11-26_14.50.39b9355.png

**Comment by 0999312** [comment]
FIXED
