### ISSUE TITLE
Add the "removeAll();" command for the CraftTweaker integration

### ISSUE THREAD

**Issue by LEWeee** [0999312/Sakura_mod#117]
`removeAll();` is a fairly common command often used in CraftTweaker, especially when making modpacks. All the command does is remove all the recipes from a machine without having to delete all of the recipes individually. This is especially useful when having duplicate machines like a Sakura Stone Mortar and a BWM Mill Stone and for one reason or another I would like to move all the recipes from the Stone Mortar to the Mill Stone (because of some benefits like requiring mechanical power to work) I first add all the recipes to the Mill Stone individually and then with a single line I remove all the recipes from the Stone Mortar.

Technically it's not too big of a deal but it's a very common command to have and I was surprised Sakura didn't support it.

**Comment by ALJ323** [comment]
it seems like it already has support for that for all of its "machines" but use "ClearAllRecipe();" instead
