### ISSUE TITLE
烹饪锅额外弹出酱油瓶

### ISSUE THREAD

**Issue by bioBean** [0999312/Sakura_mod#119]
#### MOD版本 - Mod version:

Sakura-1.0.7-1.12.2
MMLib-2.3.0
TofuCraftReload-0.1.0.9

#### Forge版本 - Forge version:

forge1.12.2-14.23.5.2855

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

同时发生于客户端和服务器

#### 完整的MOD列表 - Installed mods:

![mods](https://user-images.githubusercontent.com/10878995/115313197-bfb75300-a16a-11eb-94c8-42f0334ed5ec.png)

#### 产生Bug的步骤 - How to reproduce:

1. 在烹饪锅中制作需要用到豆腐工厂重制版的酱油瓶的食物
2. 制作完成后锅里的酱油被保留的同时额外以Entity的形式生成了两个酱油瓶物品
3. 以此通过烹饪锅可以获得无限多的耐久各不相同的酱油瓶

**Comment by bioBean** [comment]
Btw，如果可以的话能不能请大佬把新版本的源代码push到GitHub上，个人非常喜欢作者的mod，也很乐意尝试修复自己遇到的bug并提交PR。

**Comment by LonelyxiyaOVO** [comment]
我的分支版本应该修复了
