### ISSUE TITLE
Fail to compile the latest version

### ISSUE THREAD

**Issue by neohary** [0999312/Sakura_mod#128]
Hi, I was trying to compile your code into a JAR file to run in Minecraft 1.18.2, but it has failed.
The error message is here:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Sakura_mod-master'.
> Invalid patcher dependency: de.oceanlabs.mcp:mcp_config:1.18.2-20220404.173914@zip

Any ideas? I'm really like your mod and I really want to play it at the latest version.

**Comment by 0999312** [comment]
What?

**Comment by neohary** [comment]
Nevermind I worked it out, thank you for your time.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zheng ***@***.***&gt;; 
发送时间: 2022年4月26日(星期二) 上午9:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [0999312/Sakura_mod] Fail to compile the latest version (Issue #128)





 
What?
