### ISSUE TITLE
feature request: make hopper under stone_mortar transfer only processed items

### ISSUE THREAD

**Issue by KisaragiEffective** [0999312/Sakura_mod#129]
sakura version: 1.0.7-1.12.2

The stone mortar outputs ingredients first, then outputs processed items.
I thought this should output only processed ones, like `minecraft:furnace`.

built structure:
```
*
\C
```
(`*` is `sakura:stone_mortar`, `\` is `minecraft:hopper` that connecting `C`, and `C` is `minecraft:chest`)

**Comment by 0999312** [comment]
1.18.2 version will do.

**Comment by KisaragiEffective** [comment]
could it implemented also for 1.12.2 one?
I'm not sure whether 1.12.2  branch is still supported and accepts PRs if there's any.

**Comment by 0999312** [comment]
no, I can't code for 1.12.2 now.
sorry.

**Comment by KisaragiEffective** [comment]
@0999312 

> no, I can't code for 1.12.2 now.
> sorry.

nvm

> I'm not sure whether 1.12.2 branch is still supported

I'd like to confirm that 1.12.2 branch isn't in end-of-life because I'd like to submit a PR that backport it to 1.12.2 one. If you say "this mod for 1.12.2 will not update anymore," I will not submit it.

**Comment by KisaragiEffective** [comment]
@0999312 
well, so, can I submit PR to `1.12` branch to backport this behavior?

**Comment by 0999312** [comment]
sure
