### ISSUE TITLE
[1.18.2] I can't join world with Quark mod

### ISSUE THREAD

**Issue by PineJamX** [0999312/Sakura_mod#132]
Sakura ver : 1.0.1-1.18.2
Quark ver : 3.2-357
Single World

If "AutomaticRecipeUnlockModule" of Quark mod is enabled, this screen will be displayed when I join the world, and I will not be able to join the world.
![Minecraft_ 1 18 2 2022_05_23 20_36_55](https://user-images.githubusercontent.com/101681286/169811503-047a13d3-fd8d-4dd7-bfb5-62ae80939e50.png)

This is the log at that time.
[latest.log](https://github.com/0999312/Sakura_mod/files/8754174/latest.log)

This problem can be avoided by setting as follows in Quark's config.
>  "Automatic Recipe Unlock" = false

(I'm not English speaker, so it may be an unnatural sentence.)

**Comment by HiiroSaya** [comment]
same

**Comment by flin7101** [comment]
Mine crashes on world creation even with Quark set to Automatic Recipe Unlock" = false

**Comment by 0999312** [comment]
Will fix in next update about a few weeks

**Comment by 0999312** [comment]
BUG FIXED
