### ISSUE TITLE
[1.12.2]crafttweaker不能删除配方

### ISSUE THREAD

**Issue by ElinM-Challenge** [0999312/Sakura_mod#141]
模组版本：Sakura-1.0.7-1.12.2，CraftTweaker2-1.12-4.1.20.682

我在zs文件中写入：
stoneMorter.RemoveRecipe([<item:sakura:materials:5>]);
stoneMorter.AddRecipe([<sakura:buckwheat>], [<sakura:materials:5>]);
进入世界后无报错，AddRecipe生效，配方正常添加；但RemoveRecipe不生效，配方未被删除。
查看crafttweaker.log发现在读取完毕scripts后出现了这个：
[POSTINITIALIZATION][CLIENT][INFO] Removing recipes for various outputs
[AVAILABLE][CLIENT][INFO] Fixed the RecipeBook
我不清楚是不是这个导致配方不能被删除，或者是我的语句存在问题；我在社区询问并未得到答案，故来此请教！

感谢您的回复！（=￣ω￣=）

**Comment by 0999312** [comment]
1.12.2的问题无法处理，十分抱歉。

**Comment by ElinM-Challenge** [comment]
感谢您的回复！

**Comment by LonelyxiyaOVO** [comment]
我分支版本应该修复了

**Comment by ElinM-Challenge** [comment]
> 我分支版本应该修复了
> 

感谢您的贡献！😃
