### ISSUE TITLE
内存泄漏的问题

### ISSUE THREAD

**Issue by SK-Xiaohan** [0999312/Sakura_mod#144]
游戏版本1.12.2
Froge：14.23.5.2860
OptiFine：HD_U_G5
MMLib：2.3.0
Sakura：1.0.7
部分物品在玩家看向后会导致内存暴涨，直至物理内存用完然后崩溃。大多数时候转移视角并不会降低内存占用，只能重启游戏。并且会带来帧数下降。
如武士套
![image](https://github.com/0999312/Sakura_mod/assets/81475137/2bf9e084-759b-4532-ae62-124fd2f10c2f)
![image](https://github.com/0999312/Sakura_mod/assets/81475137/38399e86-9602-4b6f-a781-aec4c82158fe)

并不需要全套。
目前发现有该问题的物品：武士套（所有颜色）、所有和服.。

**Comment by SK-Xiaohan** [comment]
![image](https://github.com/0999312/Sakura_mod/assets/81475137/5463da65-2b56-40f0-a7f1-6f9203e1ebaf)

**Comment by 0999312** [comment]
1.12.2目前无法更新且未来也无法更新，十分抱歉。

**Comment by LonelyxiyaOVO** [comment]
我的分支版本应该修复了
