### ISSUE TITLE
1.18 Source? (源代码?)

### ISSUE THREAD

**Issue by SkyLordJay** [0999312/Sakura_mod#145]
I was curious about some of the clothing items that were removed in 1.18.2, and wanted to look through the source. But I see that the 1.18.2 source code branch doesn't appear to be on GitHub. I don't mind if you have gone closed source, but was just curious if we'd see the 1.18.2 code on here or not.

I love the mod and thank you for all the hard work!

----
我不知道你喜欢哪种语言，所以这是我使用谷歌翻译的尝试 
:D

我对 1.18.2 中删除的一些服装项目感到好奇，并想查看源代码。 但我发现 1.18.2 源代码分支似乎不在 GitHub 上。 我不介意你是否已经闭源，但只是好奇我们是否会在这里看到 1.18.2 代码。

我喜欢这个模组，感谢您的辛勤工作！

**Comment by 0999312** [comment]
master branch, synchronized with the current released version

**Comment by 0999312** [comment]
Clothing is WIP, but there are other lots of work need to be done, so stay tuned.
