### ISSUE TITLE
Dynamic Trees 动态的树兼容申请

### ISSUE THREAD

**Issue by touhouzun** [0999312/Sakura_mod#44]
Request : Dynamic Trees support 

https://www.curseforge.com/minecraft/mc-mods/dynamictrees

直说了吧，这个mod的点子是个天才，但ta本人不提供对其它mod的树木的兼容，想要兼容还要别的mod作者们自己动手

**Comment by 0999312** [comment]
目前放弃对动态树的支持
实在是过于繁琐，无法下笔。
