### ISSUE TITLE
0.0.7版本枫树树叶以及樱花树叶没有透明部分

### ISSUE THREAD

**Issue by illusionunit** [0999312/Sakura_mod#45]
如题，视频设置无论是高画质还是流畅画质，树叶都像是流畅画质下一团糊的样子。
难道不是bug而是特性...?

**Comment by 0999312** [comment]
请调整高清修复的配置。

**Comment by illusionunit** [comment]
尝试了原版只装forge和sakura，还是一团糊，版本为0.0.7.1
附图：
https://imgur.com/Y7oshg7
