### ISSUE TITLE
bug 使用酿酒桶崩溃

### ISSUE THREAD

**Issue by EnK1** [0999312/Sakura_mod#67]
#### MOD版本 - Mod version:

Sakura-V0.0.8-MC1.12.2.jar

#### Forge版本 - Forge version:

Minecraft Forge : 14.23.5.2838 

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

* Minecraft : 1.12.2 
* SpongeAPI : 7.1.0-ea50f0c2
* Sponge : 1.12.2-7.1.9 
* SpongeForge : 1.12.2-2838-7.1.9                  
*Minecraft Forge : 14.23.5.2838 

#### 完整的MOD列表 - Installed mods:

![]()
https://s2.ax1x.com/2020/02/11/1Iz3AP.png

## 崩溃报告的链接 - Link to full crash log

https://paste.ubuntu.com/p/Nktt2nrwZb/

#### 产生Bug的步骤 - How to reproduce:

1.把桶放入酿酒桶中
2.取出装满酒的桶，游戏崩溃退出

##服务端提示
***************************************************************************************************/
*                             Exception occurred during a PhaseState                              */
***************************************************************************************************/
* Sponge's tracking system makes a best                                                           */
* effort to not throw exceptions randomly                                                         */
* but sometimes it is inevitable. In most                                                         */
* cases, something else triggered this                                                            */
* exception and Sponge prevented a crash                                                          */
* by catching it. The following stacktrace                                                        */
* can be used to help pinpoint the cause.                                                         */
***************************************************************************************************/
* The PhaseState having an exception: Tick{TileEntity}                                            */
* The PhaseContext:                                                                               */
* org.spongepowered.asm.util.PrettyPrinter@1b7342f9                                               */
*                                                                                                 */
*  StackTrace :                                                                                   */
*     java.lang.NullPointerException: null                                                        */
*     cn.mcmod.sakura.tileentity.TileEntityBarrel.DrainInput(TileEntityBarrel.java:368)           */
*     cn.mcmod.sakura.tileentity.TileEntityBarrel.func_73660_a(TileEntityBarrel.java:83)          */
*     org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)  */
*     net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4726)                     */
*     net.minecraft.world.WorldServer.redirect$zlj000$onUpdateTileEntities(WorldServer.java:4710) */
*     net.minecraft.world.World.func_72939_s(World.java:1835)                                     */
*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3928)                         */
*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)                 */
*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)       */
*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                 */
*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                          */
*     java.lang.Thread.run(Thread.java:748)                                                       */
*                                                                                                 */
* Minecraft : 1.12.2                                                                              */
* SpongeAPI : 7.1.0-ea50f0c2                                                                      */
* Sponge : 1.12.2-7.1.9                                                                           */
* SpongeForge : 1.12.2-2838-7.1.9                                                                 */
* Minecraft Forge : 14.23.5.2838                                                                  */
***************************************************************************************************/

**Comment by 0999312** [comment]
自己去更新啊kora
