### ISSUE TITLE
[Crash] 世界生成崩溃

### ISSUE THREAD

**Issue by RainEffect** [0999312/Sakura_mod#75]
#### MOD版本 - Mod version:
v0.0.8.2

#### Forge版本 - Forge version:
14.23.5.2847

#### 单人/多人游戏？ - Singleplayer or Multiplayer:
多人游戏 服务端: CatServerAsync-1.12.2-e805c1f

#### 完整的MOD列表 - Installed mods:
服务端崩溃报告中附带

## 崩溃报告的链接 - Link to full crash log
https://paste.ubuntu.com/p/8F3fqzgrFF/

#### 产生Bug的步骤 - How to reproduce:
未知。

**Comment by 0999312** [comment]
更新0.0.9PRE
