### ISSUE TITLE
温泉装桶导致奔溃

### ISSUE THREAD

**Issue by wufe8** [0999312/Sakura_mod#76]
#### MOD版本 - Mod version:
Sakura-V0.0.8.2

#### Forge版本 - Forge version:
 forge1.12.2-14.23.5.2847

#### 单人/多人游戏？ - Singleplayer or Multiplayer:
单人游戏

#### 完整的MOD列表 - Installed mods:

zh_Name             |en_Name
----                |----
超能力              |AcademyCraft 1.1.2.jar
应用能源            |appliedenergistics2 rv6 stable 7.jar
服装工坊            |Armourers Workshop 1.7.10 0.48.3.jar
火种第一前置        |athenaeum 1.12.2 1.17.4.jar
Psi前置             |AutoRegLib 1.3 32.jar
超多生态群系        |BiomesOPlenty 1.12.2 7.0.1.2441 universal.jar
建筑                |buildcraft all 7.99.24.4.jar
存储抽屉前置        |Chameleon 1.12 4.1.3.jar
凿子                |Chisel MC1.12.2 1.0.1.44.jar
鸡骨头系列前置      |CodeChickenLib 1.12.2 3.2.3.358 universal.jar
热力前置            |CoFHCore 1.12.2 4.6.3.27 universal.jar
热力生成            |CoFHWorld 1.12.2 1.3.1.7 universal.jar
凿子前置            |CTM MC1.12.2 1.0.1.30.jar
火种第二前置        |dropt 1.12.2 1.16.1.jar
新兴技术            |EmergingTechnology 1.12.2 1.3.3.jar
末影接口前置        |EnderCore 1.12.2 0.5.73.jar
末影接口            |EnderIO 1.12.2 5.1.55.jar
无中生有            |exnihilocreatio 1.12.2 0.4.7.2.jar
更多实用            |extrautils2 1.12 1.9.9.jar
通量网络            |fluxnetworks 1.12.2 4.0.14 31.jar
重要前置            |Forgelin 1.8.4.jar
ftb前置             |FTBLib 5.4.5.0.jar
ftb任务书           |FTBQuests 1.8.0.237.jar
星系星球            |Galacticraft Planets 1.12.2 4.0.2.244.jar
星系本体            |GalacticraftCore 1.12.2 4.0.2.244.jar
格雷社区版          |gregtech 1.12.2 1.9.0.481.jar
传送枪前置          |iChunUtil 1.12.2 7.2.2.jar
工业先锋            |industrialforegoing 1.12.2 1.12.13 237.jar
工业先锋扩展        |IntegrationForegoing 1.12.2 1.9.jar
R键整理             |InventoryTweaks 1.63.jar
铁箱子              |ironchest 1.12.2 7.0.72.847.jar
ftb过滤器前置       |ItemFilters 1.0.3.12.jar
JEI                 |jei_1.12.2 4.15.0.291.jar
旅行地图            |journeymap 1.12.2 5.5.9.jar
物流管道            |logisticspipes 0.10.2.216.jar
rf工具前置          |mcjtylib 1.12 3.5.4.jar
实用物流第二前置    |MCMultiPart 2.5.3.jar
匠魂前置            |Mantle 1.12 1.3.3.55.jar
通用电力            |Mekanism 1.12.2 9.8.3.390.jar
星系前置            |MicdoodleCore 1.12.2 4.0.2.244.jar
血量显示            |Neat+1.4 17.jar
核电工艺            |NuclearCraft 2.18o 1.12.2.jar
开放式方块          |OpenBlocks 1.12.2 1.8.1.jar
开放式电脑          |OpenComputers MC1.12.2 1.7.5.192.jar
开放式方块前置      |OpenModsLib 1.12.2 0.12.2.jar
高清修复            |OptiFine_1.12.2_HD_U_F5.jar
帕秋莉手册          |Patchouli 1.0 20.jar
传送枪              |PortalGun 1.12.2 7.1.0.jar
实用物流监控2       |practicallogistics2 1.12.2 3.0.8 11.jar
Psi                 |Psi r1.1 77.jar
火种科技            |pyrotech 1.12.2 1.4.21.jar
夸克                |Quark r1.6 177.jar
红石兵工厂          |RedstoneArsenal 1.12.2 2.6.3.18 universal.jar
RF框架              |RedstoneFlux 1.12 2.1.0.6 universal.jar
rf工具              |rftools 1.12 7.73.jar
樱花                |Sakura V0.0.8.2 MC1.12.2.jar
格雷扩展            |Shadows_of_Greg 1.12.2 2.13.0.jar
实用物流第一前置    |sonarcore 1.12.2 5.0.19 20.jar
AE空间塔兼容        |spatialservermod 1.3.jar
存储抽屉            |StorageDrawers 1.12.2 5.4.0.jar
匠魂                |TConstruct 1.12.2 2.13.0.179.jar
工业先锋前置        |tesla core lib 1.12.2 1.0.16.jar
高亮显示            |theoneprobe 1.12 1.4.28.jar
热力农业            |ThermalCultivation 1.12.2 0.3.3.12 universal.jar
热力管道            |ThermalDynamics 1.12.2 2.5.5.21 universal.jar
热力膨胀本体        |ThermalExpansion 1.12.2 5.5.4.43 universal.jar
热力附加            |ThermalFoundation 1.12.2 2.6.3.27 universal.jar
热力扩展            |ThermalInnovation 1.12.2 0.3.3.12 universal.jar
传送石              |Waystones_1.12.2-4.1.0.jar

## 崩溃报告的链接 - Link to full crash log
https://paste.ubuntu.com/p/CvVD9dn2d9/

#### 产生Bug的步骤 - How to reproduce:

使用原版桶装温泉 
尝试右键装上时卡顿数十秒后崩溃
(另外高亮显示"the one probe" 显示温泉似乎没有命名--"tile.null.name")

#### 反映Bug的图片 - Pictures:
https://upload.cc/i1/2020/02/28/V8RqZr.png
https://upload.cc/i1/2020/02/28/V8RqZr.png

**Comment by 0999312** [comment]
请主动更新版本以便减少不必要的麻烦
Curseforge自寻
