### ISSUE TITLE
[建议]开放部分模组配置修改

### ISSUE THREAD

**Issue by Gan-N** [0999312/Sakura_mod#77]
希望能开放部分模组的配置调整。
1.修改竹的生成，比如一个区块内最多可以生成多少竹笋来生长竹子，而不是让竹子毫无节制的泛滥
2.指定某种树林生成，调整是生成一片树林还是零零星星的。
3.指定竹子生长高度系数，一根竹子生长极限是多高，到达生长极限后可能顶端不平整或者平整

**Comment by 0999312** [comment]
1.拒绝，除非你能保证现实竹子能够在不被人工处理的情况下控制竹笋的生长。
2.拒绝，生物群系注册相关不应该被调整。
3.拒绝，高度不应该被调整。
