### ISSUE TITLE
关于温泉的冲突问题；救救孩子

### ISSUE THREAD

**Issue by Fimbulvetrrr** [0999312/Sakura_mod#78]
#### MOD版本 - Mod version:

V0.0.8.2

#### Forge版本 - Forge version:

8.0.99.99

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

使用简单联机mod模拟的局域网小型服务器，几个朋友一起玩的

#### 完整的MOD列表 - Installed mods:

有问题的mod：
bop超多生物群系和暮色森林（生成温泉直接崩服），ic2暂时没问题，不排除有影响

## 崩溃报告的链接 - Link to full crash log

https://paste.ubuntu.com/p/BbKN9dNYPM/

#### 产生Bug的步骤 - How to reproduce:

如下，跑图、gen、崩 了：
java.lang.NullPointerException: Exception ticking world
	at cn.mcmod.sakura.world.gen.WorldGenHotSpring.func_180709_b(WorldGenHotSpring.java:16)
	at cn.mcmod.sakura.world.gen.WorldGenLoader.HotSpringGen(WorldGenLoader.java:42)

**Comment by Fimbulvetrrr** [comment]
更新了pre版本暂时没问题了

**Comment by 0999312** [comment]
请发ISSUE之前看看以前有没有类似的ISSUE
