### ISSUE TITLE
[建议] 关于锻铁炉的几个实用特性

### ISSUE THREAD

**Issue by RisingInIris2017** [0999312/Sakura_mod#80]
1. 可以考虑支持 Waila / Hwyla / TOP 显示锻铁炉的剩余燃烧时间。
目前 Waila / Hwyla / TOP 在鼠标指向燃烧中的锻铁炉时是没有显示信息的。
2. 可以考虑在 JEI 中显示玉钢、碎生铁与锻铁炉的关系，填补查询不到玉钢、碎生铁配方的空白。
3. 可以考虑支持 Blockdrops 显示挖掘锻铁炉掉落碎生铁和玉钢，并支持显示概率。
Blockdrops 的相关链接：
https://github.com/MrRiegel/BlockDrops
https://www.curseforge.com/minecraft/mc-mods/block-drops-jei-addon
4. 可以考虑支持调整碎生铁和玉钢的掉落概率。

**Comment by 0999312** [comment]
1.拒绝，实现并不是剩余燃烧时间
2.正在制作中
3.拒绝，在2的前提下不需要
4.可能添加但不保证
