### ISSUE TITLE
[Enhancement?] Config option forbidding hot spring pools in certain dimensions

### ISSUE THREAD

**Issue by yezhiyi9670** [0999312/Sakura_mod#84]
#### MOD版本 - Mod version:

`Sakura-V0.0.8.2-MC1.12.2`

#### Forge版本 - Forge version:

`Forge-14.23.5.2847`

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

在任何游戏环境均可发生。  
Occurs in both singleplayer and multiplayer environment.

#### 完整的MOD列表 - Installed mods:

游戏环境安装了 105 个 MOD。  
105 mods are installed in the gaming environment.

错误已经在只有 Sakura、TwilightForest 和 Forge 的情况下重现。  
The issue can be reproduced with only Sakura, TwilightForest and Forge.

## 崩溃报告的链接 - Link to full crash log

This is the crash report with all my mods on a physical server.  
https://pastebin.ubuntu.com/p/Gm7D2XSYdd/

#### 产生Bug的步骤 - How to reproduce:

1. Install also TwilightForest
2. Enter the TwilightForest. You probably know how to create the portal.
3. Travel and travel around in the TwilightForest. Then you may be able to see a crash.

## 修复建议 - Suggestion

Same as the title, add a config option forbidding hot spring pools in certain dimensions. Thus I'll be able to forbid hot spring pools in the Twilight Forest.

EDIT: It's also OK to just catch and ignore this error properly to prevent a crash as nothing will be unusual after a crash.

**Comment by 0999312** [comment]
UPDATE YOUR MOD AND SHUT UP

**Comment by yezhiyi9670** [comment]
OK. I see.
